---
title: 夏虫的博客
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header_pages:
- tag.md
- index.md
- about.md
style: dark
email: justwe9517@foxmail.com
description: 个人博客
baseurl: ''
url: ''
twitter_username: justwe9517
github_username: justwe9517
footer: 主题使用 jekyll-theme-console 并在它的基础上就行了大幅修改
pagination:
  enabled: true
  debug: true
  collection: posts
  per_page: 20
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: 4
    after: 4
  extension: html
  indexpage: index
autopages:
  enabled: true
  categories:
    layouts:
    - autopage_categories.html
    title: 分类 :cat
    permalink: "/autopage_categories/:cat"
  collections:
    layouts:
    - autopage_collections.html
    title: 专辑 :coll
    permalink: "/autopage_collections/:coll"
  tags:
    layouts:
    - autopage_tags.html
    title: 标签 :tag
    permalink: "/autopage_tags/:tag"
markdown: kramdown
theme: jekyll-theme-console
plugins:
- jekyll-feed
- jekyll-paginate-v2
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
